// Originally generated by VESC Tool. Preserve length checks and atomic decoding.

#include <string.h>
#include "buffer.h"
#include "conf_general.h"
#include "jfbms_slave_confparser.h"

static bool cell_counts_valid(int cells_ic1, int cells_ic2) {
	return cells_ic1 >= 3 && cells_ic1 <= 16 &&
			(cells_ic2 == 0 || (cells_ic2 >= 3 && cells_ic2 <= 16));
}

int32_t jfbms_slave_confparser_serialize_main_config_t(uint8_t *buffer, size_t capacity, const main_config_t *conf) {
	if (!buffer || !conf || capacity < SERIALIZED_CONFIG_LENGTH) return -1;
	int32_t ind = 0;

	buffer_append_uint32(buffer, MAIN_CONFIG_T_SIGNATURE, &ind);

	buffer_append_int16(buffer, conf->slave_id, &ind);
	buffer[ind++] = conf->can_baud_rate;
	buffer[ind++] = (uint8_t)conf->cells_ic1;
	buffer[ind++] = (uint8_t)conf->cells_ic2;
	buffer[ind++] = conf->temp_bq1_en;
	buffer[ind++] = conf->temp_bq2_en;
	buffer[ind++] = conf->temp_res;
	buffer_append_uint16(buffer, conf->temp_beta, &ind);

	return ind;
}

bool jfbms_slave_confparser_deserialize_main_config_t(const uint8_t *buffer, size_t length, main_config_t *conf) {
	if (!buffer || !conf || length != SERIALIZED_CONFIG_LENGTH) return false;
	main_config_t candidate = *conf;
	int32_t ind = 0;

	uint32_t signature = buffer_get_uint32(buffer, &ind);
	if (signature != MAIN_CONFIG_T_SIGNATURE) {
		return false;
	}

	candidate.slave_id = buffer_get_int16(buffer, &ind);
	candidate.can_baud_rate = buffer[ind++];
	candidate.cells_ic1 = buffer[ind++];
	candidate.cells_ic2 = buffer[ind++];
	if (!cell_counts_valid(candidate.cells_ic1, candidate.cells_ic2)) {
		return false;
	}
	if (buffer[ind] > 1 || buffer[ind + 1] > 1) return false;
	candidate.temp_bq1_en = buffer[ind++];
	candidate.temp_bq2_en = buffer[ind++];
	candidate.temp_res = buffer[ind++];
	candidate.temp_beta = buffer_get_uint16(buffer, &ind);

	if (!jfbms_slave_validate_config(&candidate)) return false;
	*conf = candidate;
	return true;
}

void jfbms_slave_confparser_set_defaults_main_config_t(main_config_t *conf) {
	conf->slave_id = CONF_SLAVE_ID;
	conf->can_baud_rate = CONF_CAN_BAUD_RATE;
	conf->cells_ic1 = CONF_CELLS_IC1;
	conf->cells_ic2 = CONF_CELLS_IC2;
	conf->temp_bq1_en = CONF_TEMP_BQ1_EN;
	conf->temp_bq2_en = CONF_TEMP_BQ2_EN;
	conf->temp_res = CONF_TEMP_RES;
	conf->temp_beta = CONF_TEMP_BETA;
}
