// Originally generated by VESC Tool. Preserve bounds checks and length-aware APIs.

#include <string.h>
#include "buffer.h"
#include "conf_general.h"
#include "jf_link_confparser.h"

// Limit every string scan by both its field size and the packet remainder.
static bool config_string(uint8_t *buffer, size_t capacity, int32_t *index,
		const char *value, size_t field_size) {
	const char *end = memchr(value, '\0', field_size);
	if (!end) return false;
	size_t count = (size_t)(end - value) + 1;
	if ((size_t)*index > capacity || count > capacity - (size_t)*index) return false;
	memcpy(buffer + *index, value, count);
	*index += (int32_t)count;
	return true;
}

static bool config_read_string(const uint8_t *buffer, size_t length, int32_t *index,
		char *value, size_t field_size) {
	if ((size_t)*index >= length) return false;
	size_t available = length - (size_t)*index;
	if (available > field_size) available = field_size;
	const uint8_t *start = buffer + *index;
	const uint8_t *end = memchr(start, '\0', available);
	if (!end) return false;
	size_t count = (size_t)(end - start) + 1;
	memcpy(value, start, count);
	*index += (int32_t)count;
	return true;
}

int32_t jf_link_confparser_serialize_main_config_t(uint8_t *buffer, size_t capacity, const main_config_t *conf) {
    if (!buffer || !conf) return -1;
    int32_t ind = 0;
#define WRITE_VALUE(size, statement) do { \
    if ((size_t)ind > capacity || (size) > capacity - (size_t)ind) return -1; \
    statement; \
} while (0)

	WRITE_VALUE(4, buffer_append_uint32(buffer, MAIN_CONFIG_T_SIGNATURE, &ind));

	WRITE_VALUE(2, buffer_append_int16(buffer, conf->controller_id, &ind));
	WRITE_VALUE(1, buffer[ind++] = conf->can_baud_rate);
	WRITE_VALUE(2, buffer_append_int16(buffer, conf->can_status_rate_hz, &ind));
	WRITE_VALUE(1, buffer[ind++] = conf->wifi_mode);
	if (!config_string(buffer, capacity, &ind, conf->wifi_sta_ssid, sizeof(conf->wifi_sta_ssid))) return -1;
	if (!config_string(buffer, capacity, &ind, conf->wifi_sta_key, sizeof(conf->wifi_sta_key))) return -1;
	if (!config_string(buffer, capacity, &ind, conf->wifi_ap_ssid, sizeof(conf->wifi_ap_ssid))) return -1;
	if (!config_string(buffer, capacity, &ind, conf->wifi_ap_key, sizeof(conf->wifi_ap_key))) return -1;
	WRITE_VALUE(1, buffer[ind++] = conf->use_tcp_local);
	WRITE_VALUE(1, buffer[ind++] = conf->use_tcp_hub);
	if (!config_string(buffer, capacity, &ind, conf->tcp_hub_url, sizeof(conf->tcp_hub_url))) return -1;
	WRITE_VALUE(2, buffer_append_uint16(buffer, conf->tcp_hub_port, &ind));
	if (!config_string(buffer, capacity, &ind, conf->tcp_hub_id, sizeof(conf->tcp_hub_id))) return -1;
	if (!config_string(buffer, capacity, &ind, conf->tcp_hub_pass, sizeof(conf->tcp_hub_pass))) return -1;
	WRITE_VALUE(1, buffer[ind++] = conf->ble_mode);
	if (!config_string(buffer, capacity, &ind, conf->ble_name, sizeof(conf->ble_name))) return -1;
	WRITE_VALUE(4, buffer_append_uint32(buffer, conf->ble_pin, &ind));
	WRITE_VALUE(4, buffer_append_uint32(buffer, conf->ble_service_capacity, &ind));
	WRITE_VALUE(4, buffer_append_uint32(buffer, conf->ble_chr_descr_capacity, &ind));
	WRITE_VALUE(1, buffer[ind++] = (uint8_t)conf->num_slaves);
	WRITE_VALUE(1, buffer[ind++] = (uint8_t)conf->slave_timeout_s);
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->vc_balance_start, &ind));
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->vc_balance_end, &ind));
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->vc_balance_min, &ind));
	WRITE_VALUE(1, buffer[ind++] = (uint8_t)conf->max_bal_ch);

#undef WRITE_VALUE
	return ind;
}

bool jf_link_confparser_deserialize_main_config_t(const uint8_t *buffer, size_t length, main_config_t *conf) {
    if (!buffer || !conf) return false;
    main_config_t candidate = *conf;
    int32_t ind = 0;
#define READ_VALUE(size, statement) do { \
    if ((size_t)ind > length || (size) > length - (size_t)ind) return false; \
    statement; \
} while (0)

	uint32_t signature;
	READ_VALUE(4, signature = buffer_get_uint32(buffer, &ind));
	if (signature != MAIN_CONFIG_T_SIGNATURE) {
		return false;
	}

	READ_VALUE(2, candidate.controller_id = buffer_get_int16(buffer, &ind));
	READ_VALUE(1, candidate.can_baud_rate = buffer[ind++]);
	READ_VALUE(2, candidate.can_status_rate_hz = buffer_get_int16(buffer, &ind));
	READ_VALUE(1, candidate.wifi_mode = buffer[ind++]);
	if (!config_read_string(buffer, length, &ind, candidate.wifi_sta_ssid, sizeof(candidate.wifi_sta_ssid))) return false;
	if (!config_read_string(buffer, length, &ind, candidate.wifi_sta_key, sizeof(candidate.wifi_sta_key))) return false;
	if (!config_read_string(buffer, length, &ind, candidate.wifi_ap_ssid, sizeof(candidate.wifi_ap_ssid))) return false;
	if (!config_read_string(buffer, length, &ind, candidate.wifi_ap_key, sizeof(candidate.wifi_ap_key))) return false;
	READ_VALUE(1, candidate.use_tcp_local = buffer[ind++]);
	READ_VALUE(1, candidate.use_tcp_hub = buffer[ind++]);
	if (!config_read_string(buffer, length, &ind, candidate.tcp_hub_url, sizeof(candidate.tcp_hub_url))) return false;
	READ_VALUE(2, candidate.tcp_hub_port = buffer_get_uint16(buffer, &ind));
	if (!config_read_string(buffer, length, &ind, candidate.tcp_hub_id, sizeof(candidate.tcp_hub_id))) return false;
	if (!config_read_string(buffer, length, &ind, candidate.tcp_hub_pass, sizeof(candidate.tcp_hub_pass))) return false;
	READ_VALUE(1, candidate.ble_mode = buffer[ind++]);
	if (!config_read_string(buffer, length, &ind, candidate.ble_name, sizeof(candidate.ble_name))) return false;
	READ_VALUE(4, candidate.ble_pin = buffer_get_uint32(buffer, &ind));
	READ_VALUE(4, candidate.ble_service_capacity = buffer_get_uint32(buffer, &ind));
	READ_VALUE(4, candidate.ble_chr_descr_capacity = buffer_get_uint32(buffer, &ind));
	READ_VALUE(1, candidate.num_slaves = buffer[ind++]);
	READ_VALUE(1, candidate.slave_timeout_s = buffer[ind++]);
	READ_VALUE(4, candidate.vc_balance_start = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(4, candidate.vc_balance_end = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(4, candidate.vc_balance_min = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(1, candidate.max_bal_ch = buffer[ind++]);

#undef READ_VALUE
	if ((size_t)ind != length || !jf_link_validate_config(&candidate)) return false;
	*conf = candidate;
	return true;
}

void jf_link_confparser_set_defaults_main_config_t(main_config_t *conf) {
	conf->controller_id = HW_DEFAULT_ID;
	conf->can_baud_rate = CONF_CAN_BAUD_RATE;
	conf->can_status_rate_hz = CONF_CAN_STATUS_RATE_HZ;
	conf->wifi_mode = CONF_WIFI_MODE;
	_Static_assert(sizeof(CONF_WIFI_STA_SSID) <= sizeof(conf->wifi_sta_ssid), "CONF_WIFI_STA_SSID exceeds its configuration field");
	strcpy(conf->wifi_sta_ssid, CONF_WIFI_STA_SSID);
	_Static_assert(sizeof(CONF_WIFI_STA_KEY) <= sizeof(conf->wifi_sta_key), "CONF_WIFI_STA_KEY exceeds its configuration field");
	strcpy(conf->wifi_sta_key, CONF_WIFI_STA_KEY);
	_Static_assert(sizeof(CONF_WIFI_AP_SSID) <= sizeof(conf->wifi_ap_ssid), "CONF_WIFI_AP_SSID exceeds its configuration field");
	strcpy(conf->wifi_ap_ssid, CONF_WIFI_AP_SSID);
	_Static_assert(sizeof(CONF_WIFI_AP_KEY) <= sizeof(conf->wifi_ap_key), "CONF_WIFI_AP_KEY exceeds its configuration field");
	strcpy(conf->wifi_ap_key, CONF_WIFI_AP_KEY);
	conf->use_tcp_local = CONF_USE_TCP_LOCAL;
	conf->use_tcp_hub = CONF_USE_TCP_HUB;
	_Static_assert(sizeof(CONF_TCP_HUB_URL) <= sizeof(conf->tcp_hub_url), "CONF_TCP_HUB_URL exceeds its configuration field");
	strcpy(conf->tcp_hub_url, CONF_TCP_HUB_URL);
	conf->tcp_hub_port = CONF_TCP_HUB_PORT;
	_Static_assert(sizeof(CONF_TCP_HUB_ID) <= sizeof(conf->tcp_hub_id), "CONF_TCP_HUB_ID exceeds its configuration field");
	strcpy(conf->tcp_hub_id, CONF_TCP_HUB_ID);
	_Static_assert(sizeof(CONF_TCP_HUB_PASS) <= sizeof(conf->tcp_hub_pass), "CONF_TCP_HUB_PASS exceeds its configuration field");
	strcpy(conf->tcp_hub_pass, CONF_TCP_HUB_PASS);
	conf->ble_mode = CONF_BLE_MODE;
	_Static_assert(sizeof(CONF_BLE_NAME) <= sizeof(conf->ble_name), "CONF_BLE_NAME exceeds its configuration field");
	strcpy(conf->ble_name, CONF_BLE_NAME);
	conf->ble_pin = CONF_BLE_PIN;
	conf->ble_service_capacity = CONF_BLE_SERVICE_CAPACITY;
	conf->ble_chr_descr_capacity = CONF_BLE_CHR_DESCR_CAPACITY;
	conf->num_slaves = CONF_NUM_SLAVES;
	conf->slave_timeout_s = CONF_SLAVE_TIMEOUT_S;
	conf->vc_balance_start = CONF_BALANCE_START;
	conf->vc_balance_end = CONF_BALANCE_END;
	conf->vc_balance_min = CONF_BALANCE_MIN;
	conf->max_bal_ch = CONF_MAX_BAL_CH;
}
