// This file is autogenerated by VESC Tool

#ifndef JFBMS32_CONFXML_H_
#define JFBMS32_CONFXML_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_MAIN_CONFIG_T__SIZE		9017

// Variables
extern uint8_t data_main_config_t_[DATA_MAIN_CONFIG_T__SIZE];

// JFBMS32_CONFXML_H_
#endif
