// Originally generated by VESC Tool; bounded APIs are maintained locally.

#ifndef JFBMS32_CONFPARSER_H_
#define JFBMS32_CONFPARSER_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// Constants
#define MAIN_CONFIG_T_SIGNATURE		1594654401
#define SERIALIZED_CONFIG_LENGTH	341

// Functions
// Returns -1 if capacity is insufficient or a string lacks a terminator.
int32_t jfbms32_confparser_serialize_main_config_t(uint8_t *buffer, size_t capacity, const main_config_t *conf);
// Requires an exact complete packet; failure leaves *conf unchanged.
bool jfbms32_confparser_deserialize_main_config_t(const uint8_t *buffer, size_t length, main_config_t *conf);
void jfbms32_confparser_set_defaults_main_config_t(main_config_t *conf);

// JFBMS32_CONFPARSER_H_
#endif
