// Originally generated by VESC Tool. Preserve the local bounds checks
// and length-aware APIs when regenerating this file.

#include <string.h>
#include <math.h>
#include "buffer.h"
#include "conf_general.h"
#include "jfbms32_confparser.h"

static bool cell_counts_valid(int cells_ic1, int cells_ic2) {
	return cells_ic1 >= 3 && cells_ic1 <= 16 &&
			(cells_ic2 == 0 || (cells_ic2 >= 3 && cells_ic2 <= 16));
}

// Limit every string scan by both its field size and the packet remainder.
static bool config_string(uint8_t *buffer, size_t capacity, int32_t *index,
		const char *value, size_t field_size) {
	const char *end = memchr(value, '\0', field_size);
	if (!end) return false;
	size_t count = (size_t)(end - value) + 1;
	if ((size_t)*index > capacity || count > capacity - (size_t)*index) return false;
	memcpy(buffer + *index, value, count);
	*index += (int32_t)count;
	return true;
}

static bool config_read_string(const uint8_t *buffer, size_t length, int32_t *index,
		char *value, size_t field_size) {
	if ((size_t)*index >= length) return false;
	size_t available = length - (size_t)*index;
	if (available > field_size) available = field_size;
	const uint8_t *start = buffer + *index;
	const uint8_t *end = memchr(start, '\0', available);
	if (!end) return false;
	size_t count = (size_t)(end - start) + 1;
	memcpy(value, start, count);
	*index += (int32_t)count;
	return true;
}

int32_t jfbms32_confparser_serialize_main_config_t(uint8_t *buffer, size_t capacity, const main_config_t *conf) {
	if (!buffer || !conf) return -1;
	int32_t ind = 0;
#define WRITE_VALUE(size, statement) do { \
	if ((size_t)ind > capacity || (size) > capacity - (size_t)ind) return -1; \
	statement; \
} while (0)

	WRITE_VALUE(4, buffer_append_uint32(buffer, MAIN_CONFIG_T_SIGNATURE, &ind));

	WRITE_VALUE(2, buffer_append_int16(buffer, conf->controller_id, &ind));
	WRITE_VALUE(1, buffer[ind++] = conf->can_baud_rate);
	WRITE_VALUE(2, buffer_append_int16(buffer, conf->can_status_rate_hz, &ind));
	WRITE_VALUE(1, buffer[ind++] = conf->wifi_mode);
	if (!config_string(buffer, capacity, &ind, conf->wifi_sta_ssid, sizeof(conf->wifi_sta_ssid))) return -1;
	if (!config_string(buffer, capacity, &ind, conf->wifi_sta_key, sizeof(conf->wifi_sta_key))) return -1;
	if (!config_string(buffer, capacity, &ind, conf->wifi_ap_ssid, sizeof(conf->wifi_ap_ssid))) return -1;
	if (!config_string(buffer, capacity, &ind, conf->wifi_ap_key, sizeof(conf->wifi_ap_key))) return -1;
	WRITE_VALUE(1, buffer[ind++] = conf->use_tcp_local);
	WRITE_VALUE(1, buffer[ind++] = conf->use_tcp_hub);
	if (!config_string(buffer, capacity, &ind, conf->tcp_hub_url, sizeof(conf->tcp_hub_url))) return -1;
	WRITE_VALUE(2, buffer_append_uint16(buffer, conf->tcp_hub_port, &ind));
	if (!config_string(buffer, capacity, &ind, conf->tcp_hub_id, sizeof(conf->tcp_hub_id))) return -1;
	if (!config_string(buffer, capacity, &ind, conf->tcp_hub_pass, sizeof(conf->tcp_hub_pass))) return -1;
	WRITE_VALUE(1, buffer[ind++] = conf->ble_mode);
	if (!config_string(buffer, capacity, &ind, conf->ble_name, sizeof(conf->ble_name))) return -1;
	WRITE_VALUE(4, buffer_append_uint32(buffer, conf->ble_pin, &ind));
	WRITE_VALUE(4, buffer_append_uint32(buffer, conf->ble_service_capacity, &ind));
	WRITE_VALUE(4, buffer_append_uint32(buffer, conf->ble_chr_descr_capacity, &ind));
	WRITE_VALUE(2, buffer_append_int16(buffer, conf->max_bal_ch, &ind));
	WRITE_VALUE(1, buffer[ind++] = (uint8_t)conf->cells_ic1);
	WRITE_VALUE(1, buffer[ind++] = (uint8_t)conf->cells_ic2);
	WRITE_VALUE(1, buffer[ind++] = (uint8_t)conf->temp_num);
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->batt_ah, &ind));
	WRITE_VALUE(1, buffer[ind++] = conf->soc_use_ah);
	WRITE_VALUE(1, buffer[ind++] = conf->block_sleep);
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->vc_empty, &ind));
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->vc_full, &ind));
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->vc_balance_start, &ind));
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->vc_balance_end, &ind));
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->vc_charge_start, &ind));
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->vc_charge_end, &ind));
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->vc_charge_min, &ind));
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->vc_balance_min, &ind));
	WRITE_VALUE(2, buffer_append_float16(buffer, conf->t_bal_max_cell, 10, &ind));
	WRITE_VALUE(2, buffer_append_float16(buffer, conf->t_bal_max_ic, 10, &ind));
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->balance_max_current, &ind));
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->min_current_ah_wh_cnt, &ind));
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->min_current_sleep, &ind));
	WRITE_VALUE(2, buffer_append_float16(buffer, conf->t_charge_max, 10, &ind));
	WRITE_VALUE(2, buffer_append_float16(buffer, conf->t_charge_max_mos, 10, &ind));
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->min_charge_current, &ind));
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->max_charge_current, &ind));
	WRITE_VALUE(2, buffer_append_float16(buffer, conf->sleep, 10, &ind));
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->soc_filter_const, &ind));
	WRITE_VALUE(2, buffer_append_float16(buffer, conf->t_charge_min, 10, &ind));
	WRITE_VALUE(1, buffer[ind++] = conf->temp_res);
	WRITE_VALUE(2, buffer_append_uint16(buffer, conf->temp_beta, &ind));
	WRITE_VALUE(2, buffer_append_int16(buffer, conf->shutdown, &ind));
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->hw_occ_current, &ind));
	WRITE_VALUE(4, buffer_append_float32_auto(buffer, conf->hw_ocd_current, &ind));
	WRITE_VALUE(1, buffer[ind++] = (uint8_t)conf->psw_scd_tres);

#undef WRITE_VALUE
	return ind;
}

bool jfbms32_confparser_deserialize_main_config_t(const uint8_t *buffer, size_t length, main_config_t *conf) {
	if (!buffer || !conf) return false;
	main_config_t candidate = *conf;
	int32_t ind = 0;
#define READ_VALUE(size, statement) do { \
	if ((size_t)ind > length || (size) > length - (size_t)ind) return false; \
	statement; \
} while (0)

	uint32_t signature;
	READ_VALUE(4, signature = buffer_get_uint32(buffer, &ind));
	if (signature != MAIN_CONFIG_T_SIGNATURE) {
		return false;
	}

	READ_VALUE(2, candidate.controller_id = buffer_get_int16(buffer, &ind));
	READ_VALUE(1, candidate.can_baud_rate = buffer[ind++]);
	READ_VALUE(2, candidate.can_status_rate_hz = buffer_get_int16(buffer, &ind));
	READ_VALUE(1, candidate.wifi_mode = buffer[ind++]);
	if (!config_read_string(buffer, length, &ind, candidate.wifi_sta_ssid, sizeof(candidate.wifi_sta_ssid))) return false;
	if (!config_read_string(buffer, length, &ind, candidate.wifi_sta_key, sizeof(candidate.wifi_sta_key))) return false;
	if (!config_read_string(buffer, length, &ind, candidate.wifi_ap_ssid, sizeof(candidate.wifi_ap_ssid))) return false;
	if (!config_read_string(buffer, length, &ind, candidate.wifi_ap_key, sizeof(candidate.wifi_ap_key))) return false;
	READ_VALUE(1, candidate.use_tcp_local = buffer[ind++]);
	READ_VALUE(1, candidate.use_tcp_hub = buffer[ind++]);
	if (!config_read_string(buffer, length, &ind, candidate.tcp_hub_url, sizeof(candidate.tcp_hub_url))) return false;
	READ_VALUE(2, candidate.tcp_hub_port = buffer_get_uint16(buffer, &ind));
	if (!config_read_string(buffer, length, &ind, candidate.tcp_hub_id, sizeof(candidate.tcp_hub_id))) return false;
	if (!config_read_string(buffer, length, &ind, candidate.tcp_hub_pass, sizeof(candidate.tcp_hub_pass))) return false;
	READ_VALUE(1, candidate.ble_mode = buffer[ind++]);
	if (!config_read_string(buffer, length, &ind, candidate.ble_name, sizeof(candidate.ble_name))) return false;
	READ_VALUE(4, candidate.ble_pin = buffer_get_uint32(buffer, &ind));
	READ_VALUE(4, candidate.ble_service_capacity = buffer_get_uint32(buffer, &ind));
	READ_VALUE(4, candidate.ble_chr_descr_capacity = buffer_get_uint32(buffer, &ind));
	READ_VALUE(2, candidate.max_bal_ch = buffer_get_int16(buffer, &ind));
	READ_VALUE(1, candidate.cells_ic1 = buffer[ind++]);
	READ_VALUE(1, candidate.cells_ic2 = buffer[ind++]);
	if (!cell_counts_valid(candidate.cells_ic1, candidate.cells_ic2)) {
		return false;
	}
	READ_VALUE(1, candidate.temp_num = buffer[ind++]);
	READ_VALUE(4, candidate.batt_ah = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(1, candidate.soc_use_ah = buffer[ind++]);
	READ_VALUE(1, candidate.block_sleep = buffer[ind++]);
	READ_VALUE(4, candidate.vc_empty = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(4, candidate.vc_full = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(4, candidate.vc_balance_start = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(4, candidate.vc_balance_end = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(4, candidate.vc_charge_start = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(4, candidate.vc_charge_end = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(4, candidate.vc_charge_min = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(4, candidate.vc_balance_min = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(2, candidate.t_bal_max_cell = buffer_get_float16(buffer, 10, &ind));
	READ_VALUE(2, candidate.t_bal_max_ic = buffer_get_float16(buffer, 10, &ind));
	READ_VALUE(4, candidate.balance_max_current = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(4, candidate.min_current_ah_wh_cnt = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(4, candidate.min_current_sleep = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(2, candidate.t_charge_max = buffer_get_float16(buffer, 10, &ind));
	READ_VALUE(2, candidate.t_charge_max_mos = buffer_get_float16(buffer, 10, &ind));
	READ_VALUE(4, candidate.min_charge_current = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(4, candidate.max_charge_current = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(2, candidate.sleep = buffer_get_float16(buffer, 10, &ind));
	READ_VALUE(4, candidate.soc_filter_const = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(2, candidate.t_charge_min = buffer_get_float16(buffer, 10, &ind));
	READ_VALUE(1, candidate.temp_res = buffer[ind++]);
	READ_VALUE(2, candidate.temp_beta = buffer_get_uint16(buffer, &ind));
	READ_VALUE(2, candidate.shutdown = buffer_get_int16(buffer, &ind));
	READ_VALUE(4, candidate.hw_occ_current = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(4, candidate.hw_ocd_current = buffer_get_float32_auto(buffer, &ind));
	READ_VALUE(1, candidate.psw_scd_tres = buffer[ind++]);
	if (!isfinite(candidate.hw_occ_current) || candidate.hw_occ_current < 4.0f ||
			candidate.hw_occ_current > 124.0f || !isfinite(candidate.hw_ocd_current) ||
			candidate.hw_ocd_current < 4.0f || candidate.hw_ocd_current > 200.0f ||
			candidate.psw_scd_tres < 0 || candidate.psw_scd_tres > 15) return false;

#undef READ_VALUE
	if ((size_t)ind != length) return false;
	*conf = candidate;
	return true;
}

void jfbms32_confparser_set_defaults_main_config_t(main_config_t *conf) {
	conf->controller_id = HW_DEFAULT_ID;
	conf->can_baud_rate = CONF_CAN_BAUD_RATE;
	conf->can_status_rate_hz = CONF_CAN_STATUS_RATE_HZ;
	conf->wifi_mode = CONF_WIFI_MODE;
	_Static_assert(sizeof(CONF_WIFI_STA_SSID) <= sizeof(conf->wifi_sta_ssid), "CONF_WIFI_STA_SSID exceeds its configuration field");
	strcpy(conf->wifi_sta_ssid, CONF_WIFI_STA_SSID);
	_Static_assert(sizeof(CONF_WIFI_STA_KEY) <= sizeof(conf->wifi_sta_key), "CONF_WIFI_STA_KEY exceeds its configuration field");
	strcpy(conf->wifi_sta_key, CONF_WIFI_STA_KEY);
	_Static_assert(sizeof(CONF_WIFI_AP_SSID) <= sizeof(conf->wifi_ap_ssid), "CONF_WIFI_AP_SSID exceeds its configuration field");
	strcpy(conf->wifi_ap_ssid, CONF_WIFI_AP_SSID);
	_Static_assert(sizeof(CONF_WIFI_AP_KEY) <= sizeof(conf->wifi_ap_key), "CONF_WIFI_AP_KEY exceeds its configuration field");
	strcpy(conf->wifi_ap_key, CONF_WIFI_AP_KEY);
	conf->use_tcp_local = CONF_USE_TCP_LOCAL;
	conf->use_tcp_hub = CONF_USE_TCP_HUB;
	_Static_assert(sizeof(CONF_TCP_HUB_URL) <= sizeof(conf->tcp_hub_url), "CONF_TCP_HUB_URL exceeds its configuration field");
	strcpy(conf->tcp_hub_url, CONF_TCP_HUB_URL);
	conf->tcp_hub_port = CONF_TCP_HUB_PORT;
	_Static_assert(sizeof(CONF_TCP_HUB_ID) <= sizeof(conf->tcp_hub_id), "CONF_TCP_HUB_ID exceeds its configuration field");
	strcpy(conf->tcp_hub_id, CONF_TCP_HUB_ID);
	_Static_assert(sizeof(CONF_TCP_HUB_PASS) <= sizeof(conf->tcp_hub_pass), "CONF_TCP_HUB_PASS exceeds its configuration field");
	strcpy(conf->tcp_hub_pass, CONF_TCP_HUB_PASS);
	conf->ble_mode = CONF_BLE_MODE;
	_Static_assert(sizeof(CONF_BLE_NAME) <= sizeof(conf->ble_name), "CONF_BLE_NAME exceeds its configuration field");
	strcpy(conf->ble_name, CONF_BLE_NAME);
	conf->ble_pin = CONF_BLE_PIN;
	conf->ble_service_capacity = CONF_BLE_SERVICE_CAPACITY;
	conf->ble_chr_descr_capacity = CONF_BLE_CHR_DESCR_CAPACITY;
	conf->max_bal_ch = CONF_MAX_BAL_CH;
	conf->cells_ic1 = CONF_CELLS_IC1;
	conf->cells_ic2 = CONF_CELLS_IC2;
	conf->temp_num = CONF_TEMP_NUM;
	conf->batt_ah = CONF_BATT_AH;
	conf->soc_use_ah = CONF_SOC_USE_AH;
	conf->block_sleep = CONF_BLOCK_SLEEP;
	conf->vc_empty = CONF_VC_EMPTY;
	conf->vc_full = CONF_VC_FULL;
	conf->vc_balance_start = CONF_BALANCE_START;
	conf->vc_balance_end = CONF_BALANCE_END;
	conf->vc_charge_start = CONF_CHARGE_START;
	conf->vc_charge_end = CONF_CHARGE_END;
	conf->vc_charge_min = CONF_CHARGE_MIN;
	conf->vc_balance_min = CONF_BALANCE_MIN;
	conf->t_bal_max_cell = CONF_T_BAL_MAX_CELL;
	conf->t_bal_max_ic = CONF_T_BAL_MAX_IC;
	conf->balance_max_current = CONF_BALANCE_MAX_CURRENT;
	conf->min_current_ah_wh_cnt = CONF_MIN_CURRENT_AH_WH_CNT;
	conf->min_current_sleep = CONF_MIN_CURRENT_SLEEP;
	conf->t_charge_max = CONF_T_CHARGE_MAX;
	conf->t_charge_max_mos = CONF_T_CHARGE_MAX_MOS;
	conf->min_charge_current = CONF_MIN_CHARGE_CURRENT;
	conf->max_charge_current = CONF_MAX_CHARGE_CURRENT;
	conf->sleep = CONF_SLEEP;
	conf->soc_filter_const = CONF_SOC_FILTER_CONST;
	conf->t_charge_min = CONF_T_CHARGE_MIN;
	conf->temp_res = CONF_TEMP_RES;
	conf->temp_beta = CONF_TEMP_BETA;
	conf->shutdown = CONF_SHUTDOWN;
	conf->hw_occ_current = CONF_HW_OCC_CURRENT;
	conf->hw_ocd_current = CONF_HW_OCD_CURRENT;
	conf->psw_scd_tres = CONF_PSW_SCD_TRES;
}
