// This file is autogenerated by VESC Tool

#ifndef JFBMS_MASTER_CONFXML_H_
#define JFBMS_MASTER_CONFXML_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_MAIN_CONFIG_T__SIZE		6389

// Variables
extern uint8_t data_main_config_t_[];

// JFBMS_MASTER_CONFXML_H_
#endif
