// JFBMS Master XML configuration
// NOTE: This is a placeholder. Use VESC Tool to generate proper compressed XML data
// from jfbms_master_settings.xml

#include "jfbms_master_confxml.h"

// Placeholder - this will be regenerated by VESC Tool from settings.xml
// For now, use a minimal valid zlib-compressed empty config
__attribute__((used)) uint8_t data_main_config_t_[1500] = {
	// Size header (2 bytes big-endian) + compressed XML placeholder
	0x00, 0x00, 0x78, 0x9c, 0x03, 0x00, 0x00, 0x00, 0x00, 0x01,
	// Padding to declared size
	0x00
};
